---@diagnostic disable: undefined-global, undefined-field
workspace "Chip8"
    configurations {"Debug", "Release"}

    newaction { -- premake5 clean
        trigger = "clean",
        description = "Clean up files generated by make",
        onStart = function()
            print("Cleaning files")
        end,
        execute = function()
            os.remove("build/obj/**.d")
            os.remove("build/obj/**.o")
            os.remove("output/**")
        end,
        onEnd = function()
            print("Clean up files")
        end
    }

    filter "configurations:Debug"
        defines {"DEBUG"}
        symbols "On"
        warnings "Everything"
        targetdir "output/debug"

    filter "configurations:Release"
        warnings "Off"
        optimize "Full"

    includedirs {"include"}

    targetdir "output/release"
    kind "ConsoleApp"
    language "C"
    libdirs {os.findlib("raylib")}
    files {
        "**.h",
        "src/**.c"
    }
    links {
        "raylib", 
        "GL", 
        "m", 
        "pthread", 
        "dl", 
        "rt", 
        "X11"
    }